# Generated by Django 3.0.8 on 2021-10-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_frete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroempresa',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
