# Generated by Django 3.0.8 on 2021-10-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_frete', '0002_auto_20211029_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
