# Generated by Django 3.0.8 on 2021-10-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_frete', '0003_auto_20211029_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cadastroempresa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
