# Generated by Django 3.0.8 on 2021-10-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_frete', '0004_auto_20211029_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='doc',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastroempresa',
            name='doc',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
