# Generated by Django 3.0.8 on 2021-10-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_frete', '0005_auto_20211029_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrooferta',
            name='amount',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastrooferta',
            name='initial_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lance',
            name='amount',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lance',
            name='value',
            field=models.FloatField(max_length=20),
        ),
    ]
