# Generated by Django 3.0.8 on 2021-10-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_frete', '0006_auto_20211029_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
