# Generated by Django 3.0.8 on 2021-10-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_frete', '0007_auto_20211029_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='amount',
            field=models.FloatField(max_length=20),
        ),
    ]
